# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('mother', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('markings', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='')),
                ('alive', models.BooleanField(default=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalGroup', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('animalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EggLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('number', models.IntegerField()),
                ('comments', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_created=django.utils.timezone.now, verbose_name='Date of record creation')),
                ('name', models.CharField(max_length=100, verbose_name='Farm name')),
                ('address', models.CharField(max_length=150, verbose_name='Farm address')),
                ('active', models.BooleanField(default=True, verbose_name='Farm active')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_created=django.utils.timezone.now, verbose_name='Date of registration for farmer')),
                ('gender', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False, verbose_name='Farmer active')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('animalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='FeedUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Forage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forage', models.CharField(max_length=100)),
                ('density', models.FloatField()),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='MedsGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField()),
                ('note', models.TextField()),
                ('filename', models.FileField(blank=True, upload_to='')),
                ('created_by', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='OtherReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_date', models.DateField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('comments', models.TextField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.OtherDest')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.OtherReason')),
            ],
        ),
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('forage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Forage')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_created=django.utils.timezone.now)),
                ('sale_tag', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField()),
                ('estimated', models.CharField(max_length=9)),
                ('price_lb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comments', models.TextField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Destination')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='SheepCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField()),
                ('eye', models.SmallIntegerField()),
                ('body', models.SmallIntegerField()),
                ('tail', models.CharField(max_length=6)),
                ('nose', models.CharField(max_length=100)),
                ('coat', models.CharField(max_length=100)),
                ('jaw', models.SmallIntegerField()),
                ('wormer', models.CharField(max_length=100)),
                ('hoof', models.CharField(max_length=3)),
                ('weight', models.IntegerField()),
                ('estimated', models.CharField(max_length=9)),
                ('comments', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_tag', models.CharField(max_length=50)),
                ('hauler', models.CharField(max_length=200)),
                ('haul_equip', models.CharField(max_length=200)),
                ('slay_date', models.DateField()),
                ('estimated', models.CharField(max_length=9)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='SlayHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slay_house', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subGroup', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('animalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('workers', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('animalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.models.animalData.AnimalSubGroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('comments', models.TextField()),
                ('workers', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('recur', models.CharField(max_length=15)),
                ('animalGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.models.animalData.AnimalSubGroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('temperature', models.SmallIntegerField(blank=True)),
                ('care', models.TextField(blank=True)),
                ('weight', models.SmallIntegerField(blank=True)),
                ('vet', models.CharField(blank=True, max_length=100)),
                ('contact', models.IntegerField(blank=True)),
                ('assistants', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Reason')),
            ],
        ),
        migrations.CreateModel(
            name='Wormer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wormer', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm')),
            ],
        ),
        migrations.AddField(
            model_name='slaughter',
            name='slay_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.SlayHouse'),
        ),
        migrations.AddField(
            model_name='medsgiven',
            name='vet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Vet'),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.FeedType'),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.FeedUnit'),
        ),
        migrations.AddField(
            model_name='feedpurchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Vendor'),
        ),
        migrations.AddField(
            model_name='egglog',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm'),
        ),
        migrations.AddField(
            model_name='destination',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm'),
        ),
        migrations.AddField(
            model_name='breed',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm'),
        ),
        migrations.AddField(
            model_name='animalgroup',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animalGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.AnimalGroup'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Farm'),
        ),
        migrations.AddField(
            model_name='animal',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Origin'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sub_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmdb.models.animalData.AnimalSubGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='subgroup',
            unique_together=set([('farm', 'animalGroup', 'subGroup')]),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together=set([('animalGroup', 'breed')]),
        ),
    ]
