# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='subGroup',
            new_name='animalSubGroup',
        ),
    ]
