# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_remove',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmdb.Animal'),
        ),
    ]
